version: '3.6'
services:
  ci:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ci

  expo-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo
      args:
        - BUILDKITE_BUILD_NUMBER
    environment:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      MAZE_BUGSNAG_API_KEY:
      DEBUG:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/test/build

  expo-publisher:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo-publisher
      args:
        # passed by bugsnag-js when it triggers a build
        - BUGSNAG_JS_BRANCH
        - BUGSNAG_JS_COMMIT
        # needed to use bugsnag-js versions hosted on artifactory
        - REGISTRY_URL
        - REG_BASIC_CREDENTIAL
        - REG_NPM_EMAIL
    environment:
      EXPO_USERNAME:
      EXPO_PASSWORD:
      EXPO_RELEASE_CHANNEL:
    networks:
      default:
        aliases:
          - maze-runner

  expo-android-builder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo-android-builder
    environment:
      DEBUG:
      EXPO_USERNAME:
      EXPO_PASSWORD:
      EXPO_RELEASE_CHANNEL:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/test/features/fixtures/build

  android-builder-base:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.android-builder-base

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-js-maze-runner}
