steps:
  #
  # License audit
  #
  - label: ':copyright: License Audit'
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa-11
    env:
      DEVELOPER_DIR: "/Applications/Xcode12.app"
    command: scripts/license_finder.sh

  #
  # Android builder base - used by React Native and React Native CLI
  #
  - label: ':docker: Build Android Builder base image'
    key: 'android-builder-base'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.9.0:
          build: android-builder-base
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:  android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base
      - docker-compose#v3.9.0:
          push: android-builder-base:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:android-builder-base

  #
  # Publish/package notifier
  #
  - label: ':docker: Prepare package.json'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    key: 'package-js'
    timeout_in_minutes: 3
    plugins:
      - docker-compose#v3.9.0:
          run: minimal-packager
    artifact_paths: min_packages.tar

  - label: ':docker: Build and publish JS packages'
    key: 'publish-js'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.9.0:
          build: publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
    env:
      BUILD_RN_WITH_LATEST_NATIVES: ${BUILD_RN_WITH_LATEST_NATIVES}


  #
  # Trigger individual pipelines
  #
  - label: 'Trigger Browser pipeline'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    depends_on: 'package-js'
    trigger: 'bugsnag-js-browser'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Trigger Node pipeline'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    depends_on: 'package-js'
    trigger: 'bugsnag-js-node'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Trigger Expo pipeline'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    depends_on: 'publish-js'
    trigger: 'bugsnag-js-expo'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Trigger React Native pipeline'
    depends_on:
      - 'publish-js'
      - 'android-builder-base'
    trigger: 'bugsnag-js-react-native'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: 'Trigger React Native CLI pipeline'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    depends_on:
      - 'publish-js'
      - 'android-builder-base'
    trigger: 'bugsnag-js-react-native-cli'
    build:
      branch: '${BUILDKITE_BRANCH}'
      commit: '${BUILDKITE_COMMIT}'
      message: '${BUILDKITE_MESSAGE}'
    async: true

  - label: ':aws-lambda: AWS Lambda tests'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    timeout_in_minutes: 35
    agents:
      queue: 'opensource-mac-cocoa-10.15'
    commands:
      # force the NPM registry as the default on CI is artifactory, which can't
      # currently install from our lockfile
      - npm ci --registry https://registry.npmjs.org
      - cd test/aws-lambda
      - bundle install
      - bundle exec maze-runner

  #
  # Core tests and checks
  #
  - label: ':docker: Build CI image'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    key: 'ci-image'
    depends_on: 'package-js'
    timeout_in_minutes: 20
    plugins:
      - artifacts#v1.5.0:
          download: min_packages.tar
      - docker-compose#v3.9.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base
      - docker-compose#v3.9.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base

  - label: 'Lint'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    depends_on: 'ci-image'
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.9.0:
        run: ci
    command: 'npm run test:lint'

  - label: 'Unit tests'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    depends_on: 'ci-image'
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.9.0:
        run: ci
    command: 'npm run test:unit'

  - label: 'Type checks/tests'
    if: build.env("BUILD_RN_WITH_LATEST_NATIVES") != "true"
    depends_on: 'ci-image'
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.9.0:
        run: ci
    command: 'npm run test:types'

  - label:  ':docker: Build expo publisher'
    key: "expo-publisher"
    timeout_in_minutes: 30
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.9.0:
          build: expo-publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-${BRANCH_NAME}
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-latest
      - docker-compose#v3.9.0:
          push:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-${BRANCH_NAME}
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-latest

  - label:  ':docker: Publish expo app'
    key: "publish-expo-app"
    depends_on: "expo-publisher"
    timeout_in_minutes: 20
    agents:
      queue: "opensource-highpower"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.9.0:
          run: expo-publisher

  - label: ':docker: Build expo maze runner image'
    key: "expo-maze-runner-image"
    timeout_in_minutes: 10
    plugins:
      - docker-compose#v3.9.0:
          build: expo-maze-runner
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
      - docker-compose#v3.9.0:
          push:
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-${BRANCH_NAME}
            - expo-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-latest

  - label:  ':docker: Build expo APK builder'
    # TODO: Pending PLAT-7743
    skip: Pending PLAT-7743
    key: "expo-android-builder"
    timeout_in_minutes: 40
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.9.0:
          build: expo-android-builder
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-${BRANCH_NAME}
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest
      - docker-compose#v3.9.0:
          push:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-${BRANCH_NAME}
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest

  - label:  ':docker: Build expo APK'
    # TODO: Pending PLAT-7743
    skip: Pending PLAT-7743
    key: "build-expo-apk"
    depends_on:
      - "publish-expo-app"
      - "expo-android-builder"
    timeout_in_minutes: 20
    agents:
      queue: "opensource-highpower"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    artifact_paths: build/output.apk
    plugins:
      - docker-compose#v3.9.0:
          run: expo-android-builder
          cache-from:
            - expo-android-builder:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-android-builder-latest

  - label: ':docker: Build expo IPA'
    key: "build-expo-ipa"
    depends_on:
      - "publish-expo-app"
    timeout_in_minutes: 20
    agents:
      queue: "opensource-mac-expo"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    artifact_paths: build/output.ipa
    commands:
      - test/expo/scripts/build-ios.sh

  - label: ':runner: expo Android 9'
    # TODO: Pending PLAT-7743
    skip: Pending PLAT-7743
    depends_on:
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.apk"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_9_0
          - --a11y-locator
          - --fail-fast
          - --retry=2
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo iOS 12'
    depends_on:
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.ipa"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_12
          - --a11y-locator
          - --appium-version=1.16.0
          - --fail-fast
          - --retry=2
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - block: "Trigger full test suite"
    key: "trigger-full-suite"

  - label: ':runner: expo Android 8'
    # TODO: Pending PLAT-7743
    skip: Pending PLAT-7743
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.apk"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_8_1
          - --a11y-locator
          - --fail-fast
          - --retry=2
          - --appium-version=1.18.0
          - --capabilities={"appWaitForLaunch":"false"}
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    soft_fail:
      - exit_status: "*"

  - label: ':runner: expo Android 7'
    # TODO: Pending PLAT-7743
    skip: Pending PLAT-7743
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.apk"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_7_1
          - --a11y-locator
          - --fail-fast
          - --retry=2
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo Android 6'
    # TODO: Pending PLAT-7743
    skip: Pending PLAT-7743
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.apk"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_6_0
          - --a11y-locator
          - --fail-fast
          - --retry=2
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo Android 5'
    # TODO: Pending PLAT-7743
    skip: Pending PLAT-7743
    depends_on:
      - "trigger-full-suite"
      - "build-expo-apk"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.apk"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.apk
          - --farm=bs
          - --device=ANDROID_5_0
          - --a11y-locator
          - --fail-fast
          - --retry=2
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo iOS 11'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.ipa"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_11
          - --a11y-locator
          - --appium-version=1.16.0
          - --fail-fast
          - --retry=2
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: ':runner: expo iOS 10'
    depends_on:
      - "trigger-full-suite"
      - "build-expo-ipa"
      - "expo-maze-runner-image"
    timeout_in_minutes: 50
    plugins:
      artifacts#v1.5.0:
        download: "build/output.ipa"
      docker-compose#v3.9.0:
        pull: expo-maze-runner
        run: expo-maze-runner
        use-aliases: true
        command:
          - --app=build/output.ipa
          - --farm=bs
          - --device=IOS_10
          - --a11y-locator
          - --fail-fast
          - --retry=2
    concurrency: 9
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
